// 身份验证与鉴权服务契约
// 编译：gf gen pb（或在项目根目录执行 make pb）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户基本信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`            // 用户ID
	Passport      string                 `protobuf:"bytes,2,opt,name=Passport,proto3" json:"Passport,omitempty"` // 账号
	Nickname      string                 `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"` // 昵称
	Roles         []string               `protobuf:"bytes,4,rep,name=Roles,proto3" json:"Roles,omitempty"`       // 角色编码列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passport      string                 `protobuf:"bytes,1,opt,name=Passport,proto3" json:"Passport,omitempty"` // v: required
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReq) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`          // 访问令牌
	RefreshToken    string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`        // 刷新令牌
	AccessExpireAt  int64                  `protobuf:"varint,3,opt,name=AccessExpireAt,proto3" json:"AccessExpireAt,omitempty"`   // 访问令牌过期时间（Unix秒）
	RefreshExpireAt int64                  `protobuf:"varint,4,opt,name=RefreshExpireAt,proto3" json:"RefreshExpireAt,omitempty"` // 刷新令牌过期时间（Unix秒）
	User            *UserInfo              `protobuf:"bytes,5,opt,name=User,proto3" json:"User,omitempty"`                        // 用户信息
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginRes) GetAccessExpireAt() int64 {
	if x != nil {
		return x.AccessExpireAt
	}
	return 0
}

func (x *LoginRes) GetRefreshExpireAt() int64 {
	if x != nil {
		return x.RefreshExpireAt
	}
	return 0
}

func (x *LoginRes) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`          // 新访问令牌
	RefreshToken    string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`        // 新刷新令牌
	AccessExpireAt  int64                  `protobuf:"varint,3,opt,name=AccessExpireAt,proto3" json:"AccessExpireAt,omitempty"`   // 访问令牌过期时间（Unix秒）
	RefreshExpireAt int64                  `protobuf:"varint,4,opt,name=RefreshExpireAt,proto3" json:"RefreshExpireAt,omitempty"` // 刷新令牌过期时间（Unix秒）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefreshTokenRes) Reset() {
	*x = RefreshTokenRes{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRes) ProtoMessage() {}

func (x *RefreshTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRes.ProtoReflect.Descriptor instead.
func (*RefreshTokenRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshTokenRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRes) GetAccessExpireAt() int64 {
	if x != nil {
		return x.AccessExpireAt
	}
	return 0
}

func (x *RefreshTokenRes) GetRefreshExpireAt() int64 {
	if x != nil {
		return x.RefreshExpireAt
	}
	return 0
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LogoutRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRes) Reset() {
	*x = LogoutRes{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRes) ProtoMessage() {}

func (x *LogoutRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRes.ProtoReflect.Descriptor instead.
func (*LogoutRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

type ParseTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTokenReq) Reset() {
	*x = ParseTokenReq{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTokenReq) ProtoMessage() {}

func (x *ParseTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTokenReq.ProtoReflect.Descriptor instead.
func (*ParseTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ParseTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ParseTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`     // 用户ID
	Passport      string                 `protobuf:"bytes,2,opt,name=Passport,proto3" json:"Passport,omitempty"`  // 账号
	Nickname      string                 `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`  // 昵称
	Roles         []string               `protobuf:"bytes,4,rep,name=Roles,proto3" json:"Roles,omitempty"`        // 角色编码列表
	IssuedAt      int64                  `protobuf:"varint,5,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"` // 签发时间（Unix秒）
	ExpireAt      int64                  `protobuf:"varint,6,opt,name=ExpireAt,proto3" json:"ExpireAt,omitempty"` // 过期时间（Unix秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTokenRes) Reset() {
	*x = ParseTokenRes{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTokenRes) ProtoMessage() {}

func (x *ParseTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTokenRes.ProtoReflect.Descriptor instead.
func (*ParseTokenRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ParseTokenRes) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ParseTokenRes) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *ParseTokenRes) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ParseTokenRes) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ParseTokenRes) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *ParseTokenRes) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

type CheckPermissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`        // v: required
	Permission    string                 `protobuf:"bytes,2,opt,name=Permission,proto3" json:"Permission,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionReq) Reset() {
	*x = CheckPermissionReq{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionReq) ProtoMessage() {}

func (x *CheckPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionReq.ProtoReflect.Descriptor instead.
func (*CheckPermissionReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *CheckPermissionReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckPermissionReq) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type CheckPermissionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granted       bool                   `protobuf:"varint,1,opt,name=Granted,proto3" json:"Granted,omitempty"` // 是否拥有权限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRes) Reset() {
	*x = CheckPermissionRes{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRes) ProtoMessage() {}

func (x *CheckPermissionRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRes.ProtoReflect.Descriptor instead.
func (*CheckPermissionRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *CheckPermissionRes) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type GetUserRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesReq) Reset() {
	*x = GetUserRolesReq{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesReq) ProtoMessage() {}

func (x *GetUserRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesReq.ProtoReflect.Descriptor instead.
func (*GetUserRolesReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserRolesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserRolesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []string               `protobuf:"bytes,1,rep,name=Roles,proto3" json:"Roles,omitempty"` // 角色编码列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRes) Reset() {
	*x = GetUserRolesRes{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRes) ProtoMessage() {}

func (x *GetUserRolesRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRes.ProtoReflect.Descriptor instead.
func (*GetUserRolesRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserRolesRes) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetUserPermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsReq) Reset() {
	*x = GetUserPermissionsReq{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsReq) ProtoMessage() {}

func (x *GetUserPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsReq.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserPermissionsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserPermissionsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=Permissions,proto3" json:"Permissions,omitempty"` // 权限码列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRes) Reset() {
	*x = GetUserPermissionsRes{}
	mi := &file_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRes) ProtoMessage() {}

func (x *GetUserPermissionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRes.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserPermissionsRes) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type DeleteAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`          // v: required
	AccessToken   string                 `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountReq) Reset() {
	*x = DeleteAccountReq{}
	mi := &file_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountReq) ProtoMessage() {}

func (x *DeleteAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountReq.ProtoReflect.Descriptor instead.
func (*DeleteAccountReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteAccountReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteAccountReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type DeleteAccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRes) Reset() {
	*x = DeleteAccountRes{}
	mi := &file_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRes) ProtoMessage() {}

func (x *DeleteAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRes.ProtoReflect.Descriptor instead.
func (*DeleteAccountRes) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{16}
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\aauth.v1\"h\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x04R\x02Id\x12\x1a\n" +
	"\bPassport\x18\x02 \x01(\tR\bPassport\x12\x1a\n" +
	"\bNickname\x18\x03 \x01(\tR\bNickname\x12\x14\n" +
	"\x05Roles\x18\x04 \x03(\tR\x05Roles\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\bPassport\x18\x01 \x01(\tR\bPassport\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"\xc9\x01\n" +
	"\bLoginRes\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\x12&\n" +
	"\x0eAccessExpireAt\x18\x03 \x01(\x03R\x0eAccessExpireAt\x12(\n" +
	"\x0fRefreshExpireAt\x18\x04 \x01(\x03R\x0fRefreshExpireAt\x12%\n" +
	"\x04User\x18\x05 \x01(\v2\x11.auth.v1.UserInfoR\x04User\"5\n" +
	"\x0fRefreshTokenReq\x12\"\n" +
	"\fRefreshToken\x18\x01 \x01(\tR\fRefreshToken\"\xa9\x01\n" +
	"\x0fRefreshTokenRes\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\x12&\n" +
	"\x0eAccessExpireAt\x18\x03 \x01(\x03R\x0eAccessExpireAt\x12(\n" +
	"\x0fRefreshExpireAt\x18\x04 \x01(\x03R\x0fRefreshExpireAt\"-\n" +
	"\tLogoutReq\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\"\v\n" +
	"\tLogoutRes\"%\n" +
	"\rParseTokenReq\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"\xad\x01\n" +
	"\rParseTokenRes\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x1a\n" +
	"\bPassport\x18\x02 \x01(\tR\bPassport\x12\x1a\n" +
	"\bNickname\x18\x03 \x01(\tR\bNickname\x12\x14\n" +
	"\x05Roles\x18\x04 \x03(\tR\x05Roles\x12\x1a\n" +
	"\bIssuedAt\x18\x05 \x01(\x03R\bIssuedAt\x12\x1a\n" +
	"\bExpireAt\x18\x06 \x01(\x03R\bExpireAt\"L\n" +
	"\x12CheckPermissionReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12\x1e\n" +
	"\n" +
	"Permission\x18\x02 \x01(\tR\n" +
	"Permission\".\n" +
	"\x12CheckPermissionRes\x12\x18\n" +
	"\aGranted\x18\x01 \x01(\bR\aGranted\")\n" +
	"\x0fGetUserRolesReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"'\n" +
	"\x0fGetUserRolesRes\x12\x14\n" +
	"\x05Roles\x18\x01 \x03(\tR\x05Roles\"/\n" +
	"\x15GetUserPermissionsReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"9\n" +
	"\x15GetUserPermissionsRes\x12 \n" +
	"\vPermissions\x18\x01 \x03(\tR\vPermissions\"L\n" +
	"\x10DeleteAccountReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\"\x12\n" +
	"\x10DeleteAccountRes2\xa7\x04\n" +
	"\x04Auth\x12/\n" +
	"\x05Login\x12\x11.auth.v1.LoginReq\x1a\x11.auth.v1.LoginRes\"\x00\x12D\n" +
	"\fRefreshToken\x12\x18.auth.v1.RefreshTokenReq\x1a\x18.auth.v1.RefreshTokenRes\"\x00\x122\n" +
	"\x06Logout\x12\x12.auth.v1.LogoutReq\x1a\x12.auth.v1.LogoutRes\"\x00\x12>\n" +
	"\n" +
	"ParseToken\x12\x16.auth.v1.ParseTokenReq\x1a\x16.auth.v1.ParseTokenRes\"\x00\x12M\n" +
	"\x0fCheckPermission\x12\x1b.auth.v1.CheckPermissionReq\x1a\x1b.auth.v1.CheckPermissionRes\"\x00\x12D\n" +
	"\fGetUserRoles\x12\x18.auth.v1.GetUserRolesReq\x1a\x18.auth.v1.GetUserRolesRes\"\x00\x12V\n" +
	"\x12GetUserPermissions\x12\x1e.auth.v1.GetUserPermissionsReq\x1a\x1e.auth.v1.GetUserPermissionsRes\"\x00\x12G\n" +
	"\rDeleteAccount\x12\x19.auth.v1.DeleteAccountReq\x1a\x19.auth.v1.DeleteAccountRes\"\x00B\x10Z\x0eapi/auth/v1;v1b\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_auth_proto_goTypes = []any{
	(*UserInfo)(nil),              // 0: auth.v1.UserInfo
	(*LoginReq)(nil),              // 1: auth.v1.LoginReq
	(*LoginRes)(nil),              // 2: auth.v1.LoginRes
	(*RefreshTokenReq)(nil),       // 3: auth.v1.RefreshTokenReq
	(*RefreshTokenRes)(nil),       // 4: auth.v1.RefreshTokenRes
	(*LogoutReq)(nil),             // 5: auth.v1.LogoutReq
	(*LogoutRes)(nil),             // 6: auth.v1.LogoutRes
	(*ParseTokenReq)(nil),         // 7: auth.v1.ParseTokenReq
	(*ParseTokenRes)(nil),         // 8: auth.v1.ParseTokenRes
	(*CheckPermissionReq)(nil),    // 9: auth.v1.CheckPermissionReq
	(*CheckPermissionRes)(nil),    // 10: auth.v1.CheckPermissionRes
	(*GetUserRolesReq)(nil),       // 11: auth.v1.GetUserRolesReq
	(*GetUserRolesRes)(nil),       // 12: auth.v1.GetUserRolesRes
	(*GetUserPermissionsReq)(nil), // 13: auth.v1.GetUserPermissionsReq
	(*GetUserPermissionsRes)(nil), // 14: auth.v1.GetUserPermissionsRes
	(*DeleteAccountReq)(nil),      // 15: auth.v1.DeleteAccountReq
	(*DeleteAccountRes)(nil),      // 16: auth.v1.DeleteAccountRes
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: auth.v1.LoginRes.User:type_name -> auth.v1.UserInfo
	1,  // 1: auth.v1.Auth.Login:input_type -> auth.v1.LoginReq
	3,  // 2: auth.v1.Auth.RefreshToken:input_type -> auth.v1.RefreshTokenReq
	5,  // 3: auth.v1.Auth.Logout:input_type -> auth.v1.LogoutReq
	7,  // 4: auth.v1.Auth.ParseToken:input_type -> auth.v1.ParseTokenReq
	9,  // 5: auth.v1.Auth.CheckPermission:input_type -> auth.v1.CheckPermissionReq
	11, // 6: auth.v1.Auth.GetUserRoles:input_type -> auth.v1.GetUserRolesReq
	13, // 7: auth.v1.Auth.GetUserPermissions:input_type -> auth.v1.GetUserPermissionsReq
	15, // 8: auth.v1.Auth.DeleteAccount:input_type -> auth.v1.DeleteAccountReq
	2,  // 9: auth.v1.Auth.Login:output_type -> auth.v1.LoginRes
	4,  // 10: auth.v1.Auth.RefreshToken:output_type -> auth.v1.RefreshTokenRes
	6,  // 11: auth.v1.Auth.Logout:output_type -> auth.v1.LogoutRes
	8,  // 12: auth.v1.Auth.ParseToken:output_type -> auth.v1.ParseTokenRes
	10, // 13: auth.v1.Auth.CheckPermission:output_type -> auth.v1.CheckPermissionRes
	12, // 14: auth.v1.Auth.GetUserRoles:output_type -> auth.v1.GetUserRolesRes
	14, // 15: auth.v1.Auth.GetUserPermissions:output_type -> auth.v1.GetUserPermissionsRes
	16, // 16: auth.v1.Auth.DeleteAccount:output_type -> auth.v1.DeleteAccountRes
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
