// 身份验证与鉴权服务契约
// 编译：gf gen pb（或在项目根目录执行 make pb）

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: oauth2.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OAuth2_GetOAuth2AuthURL_FullMethodName    = "/auth.v1.OAuth2/GetOAuth2AuthURL"
	OAuth2_OAuth2Login_FullMethodName         = "/auth.v1.OAuth2/OAuth2Login"
	OAuth2_OAuth2PreLogin_FullMethodName      = "/auth.v1.OAuth2/OAuth2PreLogin"
	OAuth2_OAuth2BindLocal_FullMethodName     = "/auth.v1.OAuth2/OAuth2BindLocal"
	OAuth2_OAuth2CreateLocal_FullMethodName   = "/auth.v1.OAuth2/OAuth2CreateLocal"
	OAuth2_BindOAuth2Account_FullMethodName   = "/auth.v1.OAuth2/BindOAuth2Account"
	OAuth2_UnbindOAuth2Account_FullMethodName = "/auth.v1.OAuth2/UnbindOAuth2Account"
	OAuth2_ListOAuth2Accounts_FullMethodName  = "/auth.v1.OAuth2/ListOAuth2Accounts"
)

// OAuth2Client is the client API for OAuth2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OAuth2Client interface {
	// OAuth2：获取第三方授权 URL（含 state 防 CSRF）
	GetOAuth2AuthURL(ctx context.Context, in *GetOAuth2AuthURLReq, opts ...grpc.CallOption) (*GetOAuth2AuthURLRes, error)
	// OAuth2：用授权码登录（换 token → 查/建用户 → 签发内部 JWT）
	OAuth2Login(ctx context.Context, in *OAuth2LoginReq, opts ...grpc.CallOption) (*OAuth2LoginRes, error)
	// OAuth2：预登录（换 token → 查绑定状态，已绑定返回 JWT，未绑定返回 pendingToken）
	OAuth2PreLogin(ctx context.Context, in *OAuth2PreLoginReq, opts ...grpc.CallOption) (*OAuth2PreLoginRes, error)
	// OAuth2：绑定到已有本地账号（通过 pendingToken + passport/password）
	OAuth2BindLocal(ctx context.Context, in *OAuth2BindLocalReq, opts ...grpc.CallOption) (*OAuth2BindLocalRes, error)
	// OAuth2：跳过绑定，自动创建新本地账号并绑定
	OAuth2CreateLocal(ctx context.Context, in *OAuth2CreateLocalReq, opts ...grpc.CallOption) (*OAuth2CreateLocalRes, error)
	// OAuth2：将第三方账号绑定到已有用户
	BindOAuth2Account(ctx context.Context, in *BindOAuth2AccountReq, opts ...grpc.CallOption) (*BindOAuth2AccountRes, error)
	// OAuth2：解绑第三方账号
	UnbindOAuth2Account(ctx context.Context, in *UnbindOAuth2AccountReq, opts ...grpc.CallOption) (*UnbindOAuth2AccountRes, error)
	// OAuth2：获取用户已绑定的第三方账号列表
	ListOAuth2Accounts(ctx context.Context, in *ListOAuth2AccountsReq, opts ...grpc.CallOption) (*ListOAuth2AccountsRes, error)
}

type oAuth2Client struct {
	cc grpc.ClientConnInterface
}

func NewOAuth2Client(cc grpc.ClientConnInterface) OAuth2Client {
	return &oAuth2Client{cc}
}

func (c *oAuth2Client) GetOAuth2AuthURL(ctx context.Context, in *GetOAuth2AuthURLReq, opts ...grpc.CallOption) (*GetOAuth2AuthURLRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOAuth2AuthURLRes)
	err := c.cc.Invoke(ctx, OAuth2_GetOAuth2AuthURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2Client) OAuth2Login(ctx context.Context, in *OAuth2LoginReq, opts ...grpc.CallOption) (*OAuth2LoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2LoginRes)
	err := c.cc.Invoke(ctx, OAuth2_OAuth2Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2Client) OAuth2PreLogin(ctx context.Context, in *OAuth2PreLoginReq, opts ...grpc.CallOption) (*OAuth2PreLoginRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2PreLoginRes)
	err := c.cc.Invoke(ctx, OAuth2_OAuth2PreLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2Client) OAuth2BindLocal(ctx context.Context, in *OAuth2BindLocalReq, opts ...grpc.CallOption) (*OAuth2BindLocalRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2BindLocalRes)
	err := c.cc.Invoke(ctx, OAuth2_OAuth2BindLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2Client) OAuth2CreateLocal(ctx context.Context, in *OAuth2CreateLocalReq, opts ...grpc.CallOption) (*OAuth2CreateLocalRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2CreateLocalRes)
	err := c.cc.Invoke(ctx, OAuth2_OAuth2CreateLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2Client) BindOAuth2Account(ctx context.Context, in *BindOAuth2AccountReq, opts ...grpc.CallOption) (*BindOAuth2AccountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindOAuth2AccountRes)
	err := c.cc.Invoke(ctx, OAuth2_BindOAuth2Account_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2Client) UnbindOAuth2Account(ctx context.Context, in *UnbindOAuth2AccountReq, opts ...grpc.CallOption) (*UnbindOAuth2AccountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindOAuth2AccountRes)
	err := c.cc.Invoke(ctx, OAuth2_UnbindOAuth2Account_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuth2Client) ListOAuth2Accounts(ctx context.Context, in *ListOAuth2AccountsReq, opts ...grpc.CallOption) (*ListOAuth2AccountsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOAuth2AccountsRes)
	err := c.cc.Invoke(ctx, OAuth2_ListOAuth2Accounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuth2Server is the server API for OAuth2 service.
// All implementations must embed UnimplementedOAuth2Server
// for forward compatibility.
type OAuth2Server interface {
	// OAuth2：获取第三方授权 URL（含 state 防 CSRF）
	GetOAuth2AuthURL(context.Context, *GetOAuth2AuthURLReq) (*GetOAuth2AuthURLRes, error)
	// OAuth2：用授权码登录（换 token → 查/建用户 → 签发内部 JWT）
	OAuth2Login(context.Context, *OAuth2LoginReq) (*OAuth2LoginRes, error)
	// OAuth2：预登录（换 token → 查绑定状态，已绑定返回 JWT，未绑定返回 pendingToken）
	OAuth2PreLogin(context.Context, *OAuth2PreLoginReq) (*OAuth2PreLoginRes, error)
	// OAuth2：绑定到已有本地账号（通过 pendingToken + passport/password）
	OAuth2BindLocal(context.Context, *OAuth2BindLocalReq) (*OAuth2BindLocalRes, error)
	// OAuth2：跳过绑定，自动创建新本地账号并绑定
	OAuth2CreateLocal(context.Context, *OAuth2CreateLocalReq) (*OAuth2CreateLocalRes, error)
	// OAuth2：将第三方账号绑定到已有用户
	BindOAuth2Account(context.Context, *BindOAuth2AccountReq) (*BindOAuth2AccountRes, error)
	// OAuth2：解绑第三方账号
	UnbindOAuth2Account(context.Context, *UnbindOAuth2AccountReq) (*UnbindOAuth2AccountRes, error)
	// OAuth2：获取用户已绑定的第三方账号列表
	ListOAuth2Accounts(context.Context, *ListOAuth2AccountsReq) (*ListOAuth2AccountsRes, error)
	mustEmbedUnimplementedOAuth2Server()
}

// UnimplementedOAuth2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAuth2Server struct{}

func (UnimplementedOAuth2Server) GetOAuth2AuthURL(context.Context, *GetOAuth2AuthURLReq) (*GetOAuth2AuthURLRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOAuth2AuthURL not implemented")
}
func (UnimplementedOAuth2Server) OAuth2Login(context.Context, *OAuth2LoginReq) (*OAuth2LoginRes, error) {
	return nil, status.Error(codes.Unimplemented, "method OAuth2Login not implemented")
}
func (UnimplementedOAuth2Server) OAuth2PreLogin(context.Context, *OAuth2PreLoginReq) (*OAuth2PreLoginRes, error) {
	return nil, status.Error(codes.Unimplemented, "method OAuth2PreLogin not implemented")
}
func (UnimplementedOAuth2Server) OAuth2BindLocal(context.Context, *OAuth2BindLocalReq) (*OAuth2BindLocalRes, error) {
	return nil, status.Error(codes.Unimplemented, "method OAuth2BindLocal not implemented")
}
func (UnimplementedOAuth2Server) OAuth2CreateLocal(context.Context, *OAuth2CreateLocalReq) (*OAuth2CreateLocalRes, error) {
	return nil, status.Error(codes.Unimplemented, "method OAuth2CreateLocal not implemented")
}
func (UnimplementedOAuth2Server) BindOAuth2Account(context.Context, *BindOAuth2AccountReq) (*BindOAuth2AccountRes, error) {
	return nil, status.Error(codes.Unimplemented, "method BindOAuth2Account not implemented")
}
func (UnimplementedOAuth2Server) UnbindOAuth2Account(context.Context, *UnbindOAuth2AccountReq) (*UnbindOAuth2AccountRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindOAuth2Account not implemented")
}
func (UnimplementedOAuth2Server) ListOAuth2Accounts(context.Context, *ListOAuth2AccountsReq) (*ListOAuth2AccountsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOAuth2Accounts not implemented")
}
func (UnimplementedOAuth2Server) mustEmbedUnimplementedOAuth2Server() {}
func (UnimplementedOAuth2Server) testEmbeddedByValue()                {}

// UnsafeOAuth2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuth2Server will
// result in compilation errors.
type UnsafeOAuth2Server interface {
	mustEmbedUnimplementedOAuth2Server()
}

func RegisterOAuth2Server(s grpc.ServiceRegistrar, srv OAuth2Server) {
	// If the following call panics, it indicates UnimplementedOAuth2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuth2_ServiceDesc, srv)
}

func _OAuth2_GetOAuth2AuthURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOAuth2AuthURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2Server).GetOAuth2AuthURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2_GetOAuth2AuthURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2Server).GetOAuth2AuthURL(ctx, req.(*GetOAuth2AuthURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2_OAuth2Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuth2LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2Server).OAuth2Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2_OAuth2Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2Server).OAuth2Login(ctx, req.(*OAuth2LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2_OAuth2PreLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuth2PreLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2Server).OAuth2PreLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2_OAuth2PreLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2Server).OAuth2PreLogin(ctx, req.(*OAuth2PreLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2_OAuth2BindLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuth2BindLocalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2Server).OAuth2BindLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2_OAuth2BindLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2Server).OAuth2BindLocal(ctx, req.(*OAuth2BindLocalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2_OAuth2CreateLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuth2CreateLocalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2Server).OAuth2CreateLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2_OAuth2CreateLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2Server).OAuth2CreateLocal(ctx, req.(*OAuth2CreateLocalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2_BindOAuth2Account_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindOAuth2AccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2Server).BindOAuth2Account(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2_BindOAuth2Account_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2Server).BindOAuth2Account(ctx, req.(*BindOAuth2AccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2_UnbindOAuth2Account_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindOAuth2AccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2Server).UnbindOAuth2Account(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2_UnbindOAuth2Account_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2Server).UnbindOAuth2Account(ctx, req.(*UnbindOAuth2AccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuth2_ListOAuth2Accounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOAuth2AccountsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuth2Server).ListOAuth2Accounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuth2_ListOAuth2Accounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuth2Server).ListOAuth2Accounts(ctx, req.(*ListOAuth2AccountsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuth2_ServiceDesc is the grpc.ServiceDesc for OAuth2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuth2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.v1.OAuth2",
	HandlerType: (*OAuth2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOAuth2AuthURL",
			Handler:    _OAuth2_GetOAuth2AuthURL_Handler,
		},
		{
			MethodName: "OAuth2Login",
			Handler:    _OAuth2_OAuth2Login_Handler,
		},
		{
			MethodName: "OAuth2PreLogin",
			Handler:    _OAuth2_OAuth2PreLogin_Handler,
		},
		{
			MethodName: "OAuth2BindLocal",
			Handler:    _OAuth2_OAuth2BindLocal_Handler,
		},
		{
			MethodName: "OAuth2CreateLocal",
			Handler:    _OAuth2_OAuth2CreateLocal_Handler,
		},
		{
			MethodName: "BindOAuth2Account",
			Handler:    _OAuth2_BindOAuth2Account_Handler,
		},
		{
			MethodName: "UnbindOAuth2Account",
			Handler:    _OAuth2_UnbindOAuth2Account_Handler,
		},
		{
			MethodName: "ListOAuth2Accounts",
			Handler:    _OAuth2_ListOAuth2Accounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth2.proto",
}
