// 身份验证与鉴权服务契约
// 编译：gf gen pb（或在项目根目录执行 make pb）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: oauth2.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OAuth2 提供商
type OAuth2Provider int32

const (
	OAuth2Provider_GITHUB  OAuth2Provider = 0
	OAuth2Provider_GOOGLE  OAuth2Provider = 1
	OAuth2Provider_WECHAT  OAuth2Provider = 2
	OAuth2Provider_WOOKOON OAuth2Provider = 3
)

// Enum value maps for OAuth2Provider.
var (
	OAuth2Provider_name = map[int32]string{
		0: "GITHUB",
		1: "GOOGLE",
		2: "WECHAT",
		3: "WOOKOON",
	}
	OAuth2Provider_value = map[string]int32{
		"GITHUB":  0,
		"GOOGLE":  1,
		"WECHAT":  2,
		"WOOKOON": 3,
	}
)

func (x OAuth2Provider) Enum() *OAuth2Provider {
	p := new(OAuth2Provider)
	*p = x
	return p
}

func (x OAuth2Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OAuth2Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_oauth2_proto_enumTypes[0].Descriptor()
}

func (OAuth2Provider) Type() protoreflect.EnumType {
	return &file_oauth2_proto_enumTypes[0]
}

func (x OAuth2Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OAuth2Provider.Descriptor instead.
func (OAuth2Provider) EnumDescriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{0}
}

type GetOAuth2AuthURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      OAuth2Provider         `protobuf:"varint,1,opt,name=Provider,proto3,enum=auth.v1.OAuth2Provider" json:"Provider,omitempty"` // v: required
	RedirectUrl   string                 `protobuf:"bytes,2,opt,name=RedirectUrl,proto3" json:"RedirectUrl,omitempty"`                        // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuth2AuthURLReq) Reset() {
	*x = GetOAuth2AuthURLReq{}
	mi := &file_oauth2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuth2AuthURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuth2AuthURLReq) ProtoMessage() {}

func (x *GetOAuth2AuthURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuth2AuthURLReq.ProtoReflect.Descriptor instead.
func (*GetOAuth2AuthURLReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{0}
}

func (x *GetOAuth2AuthURLReq) GetProvider() OAuth2Provider {
	if x != nil {
		return x.Provider
	}
	return OAuth2Provider_GITHUB
}

func (x *GetOAuth2AuthURLReq) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type GetOAuth2AuthURLRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=AuthUrl,proto3" json:"AuthUrl,omitempty"` // 授权页面 URL，前端重定向至此
	State         string                 `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`     // CSRF 防护 state（回调时需原样传回）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOAuth2AuthURLRes) Reset() {
	*x = GetOAuth2AuthURLRes{}
	mi := &file_oauth2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOAuth2AuthURLRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOAuth2AuthURLRes) ProtoMessage() {}

func (x *GetOAuth2AuthURLRes) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOAuth2AuthURLRes.ProtoReflect.Descriptor instead.
func (*GetOAuth2AuthURLRes) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{1}
}

func (x *GetOAuth2AuthURLRes) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *GetOAuth2AuthURLRes) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type OAuth2LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      OAuth2Provider         `protobuf:"varint,1,opt,name=Provider,proto3,enum=auth.v1.OAuth2Provider" json:"Provider,omitempty"` // v: required
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                      // v: required
	State         string                 `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`                                    // v: required
	RedirectUrl   string                 `protobuf:"bytes,4,opt,name=RedirectUrl,proto3" json:"RedirectUrl,omitempty"`                        // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2LoginReq) Reset() {
	*x = OAuth2LoginReq{}
	mi := &file_oauth2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2LoginReq) ProtoMessage() {}

func (x *OAuth2LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2LoginReq.ProtoReflect.Descriptor instead.
func (*OAuth2LoginReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{2}
}

func (x *OAuth2LoginReq) GetProvider() OAuth2Provider {
	if x != nil {
		return x.Provider
	}
	return OAuth2Provider_GITHUB
}

func (x *OAuth2LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OAuth2LoginReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OAuth2LoginReq) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type OAuth2LoginRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`          // 内部访问令牌
	RefreshToken    string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`        // 内部刷新令牌
	AccessExpireAt  int64                  `protobuf:"varint,3,opt,name=AccessExpireAt,proto3" json:"AccessExpireAt,omitempty"`   // 访问令牌过期时间（Unix秒）
	RefreshExpireAt int64                  `protobuf:"varint,4,opt,name=RefreshExpireAt,proto3" json:"RefreshExpireAt,omitempty"` // 刷新令牌过期时间（Unix秒）
	User            *UserInfo              `protobuf:"bytes,5,opt,name=User,proto3" json:"User,omitempty"`                        // 用户信息
	IsNewUser       bool                   `protobuf:"varint,6,opt,name=IsNewUser,proto3" json:"IsNewUser,omitempty"`             // 是否为新注册用户
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OAuth2LoginRes) Reset() {
	*x = OAuth2LoginRes{}
	mi := &file_oauth2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2LoginRes) ProtoMessage() {}

func (x *OAuth2LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2LoginRes.ProtoReflect.Descriptor instead.
func (*OAuth2LoginRes) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{3}
}

func (x *OAuth2LoginRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuth2LoginRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2LoginRes) GetAccessExpireAt() int64 {
	if x != nil {
		return x.AccessExpireAt
	}
	return 0
}

func (x *OAuth2LoginRes) GetRefreshExpireAt() int64 {
	if x != nil {
		return x.RefreshExpireAt
	}
	return 0
}

func (x *OAuth2LoginRes) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *OAuth2LoginRes) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

type BindOAuth2AccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`                                 // v: required
	Provider      OAuth2Provider         `protobuf:"varint,2,opt,name=Provider,proto3,enum=auth.v1.OAuth2Provider" json:"Provider,omitempty"` // v: required
	Code          string                 `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`                                      // v: required
	State         string                 `protobuf:"bytes,4,opt,name=State,proto3" json:"State,omitempty"`                                    // v: required
	RedirectUrl   string                 `protobuf:"bytes,5,opt,name=RedirectUrl,proto3" json:"RedirectUrl,omitempty"`                        // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOAuth2AccountReq) Reset() {
	*x = BindOAuth2AccountReq{}
	mi := &file_oauth2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOAuth2AccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOAuth2AccountReq) ProtoMessage() {}

func (x *BindOAuth2AccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOAuth2AccountReq.ProtoReflect.Descriptor instead.
func (*BindOAuth2AccountReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{4}
}

func (x *BindOAuth2AccountReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BindOAuth2AccountReq) GetProvider() OAuth2Provider {
	if x != nil {
		return x.Provider
	}
	return OAuth2Provider_GITHUB
}

func (x *BindOAuth2AccountReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BindOAuth2AccountReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *BindOAuth2AccountReq) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type BindOAuth2AccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOAuth2AccountRes) Reset() {
	*x = BindOAuth2AccountRes{}
	mi := &file_oauth2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOAuth2AccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOAuth2AccountRes) ProtoMessage() {}

func (x *BindOAuth2AccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOAuth2AccountRes.ProtoReflect.Descriptor instead.
func (*BindOAuth2AccountRes) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{5}
}

type UnbindOAuth2AccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`                                 // v: required
	Provider      OAuth2Provider         `protobuf:"varint,2,opt,name=Provider,proto3,enum=auth.v1.OAuth2Provider" json:"Provider,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindOAuth2AccountReq) Reset() {
	*x = UnbindOAuth2AccountReq{}
	mi := &file_oauth2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindOAuth2AccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindOAuth2AccountReq) ProtoMessage() {}

func (x *UnbindOAuth2AccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindOAuth2AccountReq.ProtoReflect.Descriptor instead.
func (*UnbindOAuth2AccountReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{6}
}

func (x *UnbindOAuth2AccountReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnbindOAuth2AccountReq) GetProvider() OAuth2Provider {
	if x != nil {
		return x.Provider
	}
	return OAuth2Provider_GITHUB
}

type UnbindOAuth2AccountRes struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountDeleted bool                   `protobuf:"varint,1,opt,name=AccountDeleted,proto3" json:"AccountDeleted,omitempty"` // 解绑后本地账户是否已被级联删除（无密码的第三方账号会被删除）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnbindOAuth2AccountRes) Reset() {
	*x = UnbindOAuth2AccountRes{}
	mi := &file_oauth2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindOAuth2AccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindOAuth2AccountRes) ProtoMessage() {}

func (x *UnbindOAuth2AccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindOAuth2AccountRes.ProtoReflect.Descriptor instead.
func (*UnbindOAuth2AccountRes) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{7}
}

func (x *UnbindOAuth2AccountRes) GetAccountDeleted() bool {
	if x != nil {
		return x.AccountDeleted
	}
	return false
}

type ListOAuth2AccountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOAuth2AccountsReq) Reset() {
	*x = ListOAuth2AccountsReq{}
	mi := &file_oauth2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOAuth2AccountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuth2AccountsReq) ProtoMessage() {}

func (x *ListOAuth2AccountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuth2AccountsReq.ProtoReflect.Descriptor instead.
func (*ListOAuth2AccountsReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{8}
}

func (x *ListOAuth2AccountsReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type OAuth2AccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      OAuth2Provider         `protobuf:"varint,1,opt,name=Provider,proto3,enum=auth.v1.OAuth2Provider" json:"Provider,omitempty"` // 提供商
	OpenId        string                 `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`                                  // 第三方用户唯一标识
	Nickname      string                 `protobuf:"bytes,3,opt,name=Nickname,proto3" json:"Nickname,omitempty"`                              // 第三方昵称
	Avatar        string                 `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`                                  // 第三方头像 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2AccountInfo) Reset() {
	*x = OAuth2AccountInfo{}
	mi := &file_oauth2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2AccountInfo) ProtoMessage() {}

func (x *OAuth2AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2AccountInfo.ProtoReflect.Descriptor instead.
func (*OAuth2AccountInfo) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{9}
}

func (x *OAuth2AccountInfo) GetProvider() OAuth2Provider {
	if x != nil {
		return x.Provider
	}
	return OAuth2Provider_GITHUB
}

func (x *OAuth2AccountInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *OAuth2AccountInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *OAuth2AccountInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type ListOAuth2AccountsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*OAuth2AccountInfo   `protobuf:"bytes,1,rep,name=Accounts,proto3" json:"Accounts,omitempty"` // 已绑定的第三方账号列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOAuth2AccountsRes) Reset() {
	*x = ListOAuth2AccountsRes{}
	mi := &file_oauth2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOAuth2AccountsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOAuth2AccountsRes) ProtoMessage() {}

func (x *ListOAuth2AccountsRes) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOAuth2AccountsRes.ProtoReflect.Descriptor instead.
func (*ListOAuth2AccountsRes) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{10}
}

func (x *ListOAuth2AccountsRes) GetAccounts() []*OAuth2AccountInfo {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type OAuth2PreLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      OAuth2Provider         `protobuf:"varint,1,opt,name=Provider,proto3,enum=auth.v1.OAuth2Provider" json:"Provider,omitempty"` // v: required
	Code          string                 `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`                                      // v: required
	State         string                 `protobuf:"bytes,3,opt,name=State,proto3" json:"State,omitempty"`                                    // v: required
	RedirectUrl   string                 `protobuf:"bytes,4,opt,name=RedirectUrl,proto3" json:"RedirectUrl,omitempty"`                        // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2PreLoginReq) Reset() {
	*x = OAuth2PreLoginReq{}
	mi := &file_oauth2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2PreLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2PreLoginReq) ProtoMessage() {}

func (x *OAuth2PreLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2PreLoginReq.ProtoReflect.Descriptor instead.
func (*OAuth2PreLoginReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{11}
}

func (x *OAuth2PreLoginReq) GetProvider() OAuth2Provider {
	if x != nil {
		return x.Provider
	}
	return OAuth2Provider_GITHUB
}

func (x *OAuth2PreLoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OAuth2PreLoginReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OAuth2PreLoginReq) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type OAuth2PreLoginRes struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	IsBound bool                   `protobuf:"varint,1,opt,name=IsBound,proto3" json:"IsBound,omitempty"` // 是否已绑定本地账号
	// 已绑定时以下字段有效
	AccessToken     string    `protobuf:"bytes,2,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken    string    `protobuf:"bytes,3,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	AccessExpireAt  int64     `protobuf:"varint,4,opt,name=AccessExpireAt,proto3" json:"AccessExpireAt,omitempty"`
	RefreshExpireAt int64     `protobuf:"varint,5,opt,name=RefreshExpireAt,proto3" json:"RefreshExpireAt,omitempty"`
	User            *UserInfo `protobuf:"bytes,6,opt,name=User,proto3" json:"User,omitempty"`
	// 未绑定时以下字段有效
	PendingToken  string `protobuf:"bytes,7,opt,name=PendingToken,proto3" json:"PendingToken,omitempty"`  // 待绑定令牌（用于后续绑定/创建）
	Nickname      string `protobuf:"bytes,8,opt,name=Nickname,proto3" json:"Nickname,omitempty"`          // 第三方昵称
	Avatar        string `protobuf:"bytes,9,opt,name=Avatar,proto3" json:"Avatar,omitempty"`              // 第三方头像
	ProviderName  string `protobuf:"bytes,10,opt,name=ProviderName,proto3" json:"ProviderName,omitempty"` // 提供商名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2PreLoginRes) Reset() {
	*x = OAuth2PreLoginRes{}
	mi := &file_oauth2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2PreLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2PreLoginRes) ProtoMessage() {}

func (x *OAuth2PreLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2PreLoginRes.ProtoReflect.Descriptor instead.
func (*OAuth2PreLoginRes) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{12}
}

func (x *OAuth2PreLoginRes) GetIsBound() bool {
	if x != nil {
		return x.IsBound
	}
	return false
}

func (x *OAuth2PreLoginRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuth2PreLoginRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2PreLoginRes) GetAccessExpireAt() int64 {
	if x != nil {
		return x.AccessExpireAt
	}
	return 0
}

func (x *OAuth2PreLoginRes) GetRefreshExpireAt() int64 {
	if x != nil {
		return x.RefreshExpireAt
	}
	return 0
}

func (x *OAuth2PreLoginRes) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *OAuth2PreLoginRes) GetPendingToken() string {
	if x != nil {
		return x.PendingToken
	}
	return ""
}

func (x *OAuth2PreLoginRes) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *OAuth2PreLoginRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *OAuth2PreLoginRes) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type OAuth2BindLocalReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PendingToken  string                 `protobuf:"bytes,1,opt,name=PendingToken,proto3" json:"PendingToken,omitempty"` // v: required
	Passport      string                 `protobuf:"bytes,2,opt,name=Passport,proto3" json:"Passport,omitempty"`         // v: required
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`         // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2BindLocalReq) Reset() {
	*x = OAuth2BindLocalReq{}
	mi := &file_oauth2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2BindLocalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2BindLocalReq) ProtoMessage() {}

func (x *OAuth2BindLocalReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2BindLocalReq.ProtoReflect.Descriptor instead.
func (*OAuth2BindLocalReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{13}
}

func (x *OAuth2BindLocalReq) GetPendingToken() string {
	if x != nil {
		return x.PendingToken
	}
	return ""
}

func (x *OAuth2BindLocalReq) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

func (x *OAuth2BindLocalReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type OAuth2BindLocalRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	AccessExpireAt  int64                  `protobuf:"varint,3,opt,name=AccessExpireAt,proto3" json:"AccessExpireAt,omitempty"`
	RefreshExpireAt int64                  `protobuf:"varint,4,opt,name=RefreshExpireAt,proto3" json:"RefreshExpireAt,omitempty"`
	User            *UserInfo              `protobuf:"bytes,5,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OAuth2BindLocalRes) Reset() {
	*x = OAuth2BindLocalRes{}
	mi := &file_oauth2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2BindLocalRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2BindLocalRes) ProtoMessage() {}

func (x *OAuth2BindLocalRes) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2BindLocalRes.ProtoReflect.Descriptor instead.
func (*OAuth2BindLocalRes) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{14}
}

func (x *OAuth2BindLocalRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuth2BindLocalRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2BindLocalRes) GetAccessExpireAt() int64 {
	if x != nil {
		return x.AccessExpireAt
	}
	return 0
}

func (x *OAuth2BindLocalRes) GetRefreshExpireAt() int64 {
	if x != nil {
		return x.RefreshExpireAt
	}
	return 0
}

func (x *OAuth2BindLocalRes) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type OAuth2CreateLocalReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PendingToken  string                 `protobuf:"bytes,1,opt,name=PendingToken,proto3" json:"PendingToken,omitempty"` // v: required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2CreateLocalReq) Reset() {
	*x = OAuth2CreateLocalReq{}
	mi := &file_oauth2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2CreateLocalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2CreateLocalReq) ProtoMessage() {}

func (x *OAuth2CreateLocalReq) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2CreateLocalReq.ProtoReflect.Descriptor instead.
func (*OAuth2CreateLocalReq) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{15}
}

func (x *OAuth2CreateLocalReq) GetPendingToken() string {
	if x != nil {
		return x.PendingToken
	}
	return ""
}

type OAuth2CreateLocalRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	RefreshToken    string                 `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	AccessExpireAt  int64                  `protobuf:"varint,3,opt,name=AccessExpireAt,proto3" json:"AccessExpireAt,omitempty"`
	RefreshExpireAt int64                  `protobuf:"varint,4,opt,name=RefreshExpireAt,proto3" json:"RefreshExpireAt,omitempty"`
	User            *UserInfo              `protobuf:"bytes,5,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OAuth2CreateLocalRes) Reset() {
	*x = OAuth2CreateLocalRes{}
	mi := &file_oauth2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2CreateLocalRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2CreateLocalRes) ProtoMessage() {}

func (x *OAuth2CreateLocalRes) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2CreateLocalRes.ProtoReflect.Descriptor instead.
func (*OAuth2CreateLocalRes) Descriptor() ([]byte, []int) {
	return file_oauth2_proto_rawDescGZIP(), []int{16}
}

func (x *OAuth2CreateLocalRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuth2CreateLocalRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2CreateLocalRes) GetAccessExpireAt() int64 {
	if x != nil {
		return x.AccessExpireAt
	}
	return 0
}

func (x *OAuth2CreateLocalRes) GetRefreshExpireAt() int64 {
	if x != nil {
		return x.RefreshExpireAt
	}
	return 0
}

func (x *OAuth2CreateLocalRes) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

var File_oauth2_proto protoreflect.FileDescriptor

const file_oauth2_proto_rawDesc = "" +
	"\n" +
	"\foauth2.proto\x12\aauth.v1\x1a\n" +
	"auth.proto\"l\n" +
	"\x13GetOAuth2AuthURLReq\x123\n" +
	"\bProvider\x18\x01 \x01(\x0e2\x17.auth.v1.OAuth2ProviderR\bProvider\x12 \n" +
	"\vRedirectUrl\x18\x02 \x01(\tR\vRedirectUrl\"E\n" +
	"\x13GetOAuth2AuthURLRes\x12\x18\n" +
	"\aAuthUrl\x18\x01 \x01(\tR\aAuthUrl\x12\x14\n" +
	"\x05State\x18\x02 \x01(\tR\x05State\"\x91\x01\n" +
	"\x0eOAuth2LoginReq\x123\n" +
	"\bProvider\x18\x01 \x01(\x0e2\x17.auth.v1.OAuth2ProviderR\bProvider\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\x12\x14\n" +
	"\x05State\x18\x03 \x01(\tR\x05State\x12 \n" +
	"\vRedirectUrl\x18\x04 \x01(\tR\vRedirectUrl\"\xed\x01\n" +
	"\x0eOAuth2LoginRes\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\x12&\n" +
	"\x0eAccessExpireAt\x18\x03 \x01(\x03R\x0eAccessExpireAt\x12(\n" +
	"\x0fRefreshExpireAt\x18\x04 \x01(\x03R\x0fRefreshExpireAt\x12%\n" +
	"\x04User\x18\x05 \x01(\v2\x11.auth.v1.UserInfoR\x04User\x12\x1c\n" +
	"\tIsNewUser\x18\x06 \x01(\bR\tIsNewUser\"\xaf\x01\n" +
	"\x14BindOAuth2AccountReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x123\n" +
	"\bProvider\x18\x02 \x01(\x0e2\x17.auth.v1.OAuth2ProviderR\bProvider\x12\x12\n" +
	"\x04Code\x18\x03 \x01(\tR\x04Code\x12\x14\n" +
	"\x05State\x18\x04 \x01(\tR\x05State\x12 \n" +
	"\vRedirectUrl\x18\x05 \x01(\tR\vRedirectUrl\"\x16\n" +
	"\x14BindOAuth2AccountRes\"e\n" +
	"\x16UnbindOAuth2AccountReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\x123\n" +
	"\bProvider\x18\x02 \x01(\x0e2\x17.auth.v1.OAuth2ProviderR\bProvider\"@\n" +
	"\x16UnbindOAuth2AccountRes\x12&\n" +
	"\x0eAccountDeleted\x18\x01 \x01(\bR\x0eAccountDeleted\"/\n" +
	"\x15ListOAuth2AccountsReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x04R\x06UserId\"\x94\x01\n" +
	"\x11OAuth2AccountInfo\x123\n" +
	"\bProvider\x18\x01 \x01(\x0e2\x17.auth.v1.OAuth2ProviderR\bProvider\x12\x16\n" +
	"\x06OpenId\x18\x02 \x01(\tR\x06OpenId\x12\x1a\n" +
	"\bNickname\x18\x03 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x04 \x01(\tR\x06Avatar\"O\n" +
	"\x15ListOAuth2AccountsRes\x126\n" +
	"\bAccounts\x18\x01 \x03(\v2\x1a.auth.v1.OAuth2AccountInfoR\bAccounts\"\x94\x01\n" +
	"\x11OAuth2PreLoginReq\x123\n" +
	"\bProvider\x18\x01 \x01(\x0e2\x17.auth.v1.OAuth2ProviderR\bProvider\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\tR\x04Code\x12\x14\n" +
	"\x05State\x18\x03 \x01(\tR\x05State\x12 \n" +
	"\vRedirectUrl\x18\x04 \x01(\tR\vRedirectUrl\"\xe8\x02\n" +
	"\x11OAuth2PreLoginRes\x12\x18\n" +
	"\aIsBound\x18\x01 \x01(\bR\aIsBound\x12 \n" +
	"\vAccessToken\x18\x02 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x03 \x01(\tR\fRefreshToken\x12&\n" +
	"\x0eAccessExpireAt\x18\x04 \x01(\x03R\x0eAccessExpireAt\x12(\n" +
	"\x0fRefreshExpireAt\x18\x05 \x01(\x03R\x0fRefreshExpireAt\x12%\n" +
	"\x04User\x18\x06 \x01(\v2\x11.auth.v1.UserInfoR\x04User\x12\"\n" +
	"\fPendingToken\x18\a \x01(\tR\fPendingToken\x12\x1a\n" +
	"\bNickname\x18\b \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\t \x01(\tR\x06Avatar\x12\"\n" +
	"\fProviderName\x18\n" +
	" \x01(\tR\fProviderName\"p\n" +
	"\x12OAuth2BindLocalReq\x12\"\n" +
	"\fPendingToken\x18\x01 \x01(\tR\fPendingToken\x12\x1a\n" +
	"\bPassport\x18\x02 \x01(\tR\bPassport\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"\xd3\x01\n" +
	"\x12OAuth2BindLocalRes\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\x12&\n" +
	"\x0eAccessExpireAt\x18\x03 \x01(\x03R\x0eAccessExpireAt\x12(\n" +
	"\x0fRefreshExpireAt\x18\x04 \x01(\x03R\x0fRefreshExpireAt\x12%\n" +
	"\x04User\x18\x05 \x01(\v2\x11.auth.v1.UserInfoR\x04User\":\n" +
	"\x14OAuth2CreateLocalReq\x12\"\n" +
	"\fPendingToken\x18\x01 \x01(\tR\fPendingToken\"\xd5\x01\n" +
	"\x14OAuth2CreateLocalRes\x12 \n" +
	"\vAccessToken\x18\x01 \x01(\tR\vAccessToken\x12\"\n" +
	"\fRefreshToken\x18\x02 \x01(\tR\fRefreshToken\x12&\n" +
	"\x0eAccessExpireAt\x18\x03 \x01(\x03R\x0eAccessExpireAt\x12(\n" +
	"\x0fRefreshExpireAt\x18\x04 \x01(\x03R\x0fRefreshExpireAt\x12%\n" +
	"\x04User\x18\x05 \x01(\v2\x11.auth.v1.UserInfoR\x04User*A\n" +
	"\x0eOAuth2Provider\x12\n" +
	"\n" +
	"\x06GITHUB\x10\x00\x12\n" +
	"\n" +
	"\x06GOOGLE\x10\x01\x12\n" +
	"\n" +
	"\x06WECHAT\x10\x02\x12\v\n" +
	"\aWOOKOON\x10\x032\x95\x05\n" +
	"\x06OAuth2\x12P\n" +
	"\x10GetOAuth2AuthURL\x12\x1c.auth.v1.GetOAuth2AuthURLReq\x1a\x1c.auth.v1.GetOAuth2AuthURLRes\"\x00\x12A\n" +
	"\vOAuth2Login\x12\x17.auth.v1.OAuth2LoginReq\x1a\x17.auth.v1.OAuth2LoginRes\"\x00\x12J\n" +
	"\x0eOAuth2PreLogin\x12\x1a.auth.v1.OAuth2PreLoginReq\x1a\x1a.auth.v1.OAuth2PreLoginRes\"\x00\x12M\n" +
	"\x0fOAuth2BindLocal\x12\x1b.auth.v1.OAuth2BindLocalReq\x1a\x1b.auth.v1.OAuth2BindLocalRes\"\x00\x12S\n" +
	"\x11OAuth2CreateLocal\x12\x1d.auth.v1.OAuth2CreateLocalReq\x1a\x1d.auth.v1.OAuth2CreateLocalRes\"\x00\x12S\n" +
	"\x11BindOAuth2Account\x12\x1d.auth.v1.BindOAuth2AccountReq\x1a\x1d.auth.v1.BindOAuth2AccountRes\"\x00\x12Y\n" +
	"\x13UnbindOAuth2Account\x12\x1f.auth.v1.UnbindOAuth2AccountReq\x1a\x1f.auth.v1.UnbindOAuth2AccountRes\"\x00\x12V\n" +
	"\x12ListOAuth2Accounts\x12\x1e.auth.v1.ListOAuth2AccountsReq\x1a\x1e.auth.v1.ListOAuth2AccountsRes\"\x00B\x10Z\x0eapi/auth/v1;v1b\x06proto3"

var (
	file_oauth2_proto_rawDescOnce sync.Once
	file_oauth2_proto_rawDescData []byte
)

func file_oauth2_proto_rawDescGZIP() []byte {
	file_oauth2_proto_rawDescOnce.Do(func() {
		file_oauth2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauth2_proto_rawDesc), len(file_oauth2_proto_rawDesc)))
	})
	return file_oauth2_proto_rawDescData
}

var file_oauth2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oauth2_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_oauth2_proto_goTypes = []any{
	(OAuth2Provider)(0),            // 0: auth.v1.OAuth2Provider
	(*GetOAuth2AuthURLReq)(nil),    // 1: auth.v1.GetOAuth2AuthURLReq
	(*GetOAuth2AuthURLRes)(nil),    // 2: auth.v1.GetOAuth2AuthURLRes
	(*OAuth2LoginReq)(nil),         // 3: auth.v1.OAuth2LoginReq
	(*OAuth2LoginRes)(nil),         // 4: auth.v1.OAuth2LoginRes
	(*BindOAuth2AccountReq)(nil),   // 5: auth.v1.BindOAuth2AccountReq
	(*BindOAuth2AccountRes)(nil),   // 6: auth.v1.BindOAuth2AccountRes
	(*UnbindOAuth2AccountReq)(nil), // 7: auth.v1.UnbindOAuth2AccountReq
	(*UnbindOAuth2AccountRes)(nil), // 8: auth.v1.UnbindOAuth2AccountRes
	(*ListOAuth2AccountsReq)(nil),  // 9: auth.v1.ListOAuth2AccountsReq
	(*OAuth2AccountInfo)(nil),      // 10: auth.v1.OAuth2AccountInfo
	(*ListOAuth2AccountsRes)(nil),  // 11: auth.v1.ListOAuth2AccountsRes
	(*OAuth2PreLoginReq)(nil),      // 12: auth.v1.OAuth2PreLoginReq
	(*OAuth2PreLoginRes)(nil),      // 13: auth.v1.OAuth2PreLoginRes
	(*OAuth2BindLocalReq)(nil),     // 14: auth.v1.OAuth2BindLocalReq
	(*OAuth2BindLocalRes)(nil),     // 15: auth.v1.OAuth2BindLocalRes
	(*OAuth2CreateLocalReq)(nil),   // 16: auth.v1.OAuth2CreateLocalReq
	(*OAuth2CreateLocalRes)(nil),   // 17: auth.v1.OAuth2CreateLocalRes
	(*UserInfo)(nil),               // 18: auth.v1.UserInfo
}
var file_oauth2_proto_depIdxs = []int32{
	0,  // 0: auth.v1.GetOAuth2AuthURLReq.Provider:type_name -> auth.v1.OAuth2Provider
	0,  // 1: auth.v1.OAuth2LoginReq.Provider:type_name -> auth.v1.OAuth2Provider
	18, // 2: auth.v1.OAuth2LoginRes.User:type_name -> auth.v1.UserInfo
	0,  // 3: auth.v1.BindOAuth2AccountReq.Provider:type_name -> auth.v1.OAuth2Provider
	0,  // 4: auth.v1.UnbindOAuth2AccountReq.Provider:type_name -> auth.v1.OAuth2Provider
	0,  // 5: auth.v1.OAuth2AccountInfo.Provider:type_name -> auth.v1.OAuth2Provider
	10, // 6: auth.v1.ListOAuth2AccountsRes.Accounts:type_name -> auth.v1.OAuth2AccountInfo
	0,  // 7: auth.v1.OAuth2PreLoginReq.Provider:type_name -> auth.v1.OAuth2Provider
	18, // 8: auth.v1.OAuth2PreLoginRes.User:type_name -> auth.v1.UserInfo
	18, // 9: auth.v1.OAuth2BindLocalRes.User:type_name -> auth.v1.UserInfo
	18, // 10: auth.v1.OAuth2CreateLocalRes.User:type_name -> auth.v1.UserInfo
	1,  // 11: auth.v1.OAuth2.GetOAuth2AuthURL:input_type -> auth.v1.GetOAuth2AuthURLReq
	3,  // 12: auth.v1.OAuth2.OAuth2Login:input_type -> auth.v1.OAuth2LoginReq
	12, // 13: auth.v1.OAuth2.OAuth2PreLogin:input_type -> auth.v1.OAuth2PreLoginReq
	14, // 14: auth.v1.OAuth2.OAuth2BindLocal:input_type -> auth.v1.OAuth2BindLocalReq
	16, // 15: auth.v1.OAuth2.OAuth2CreateLocal:input_type -> auth.v1.OAuth2CreateLocalReq
	5,  // 16: auth.v1.OAuth2.BindOAuth2Account:input_type -> auth.v1.BindOAuth2AccountReq
	7,  // 17: auth.v1.OAuth2.UnbindOAuth2Account:input_type -> auth.v1.UnbindOAuth2AccountReq
	9,  // 18: auth.v1.OAuth2.ListOAuth2Accounts:input_type -> auth.v1.ListOAuth2AccountsReq
	2,  // 19: auth.v1.OAuth2.GetOAuth2AuthURL:output_type -> auth.v1.GetOAuth2AuthURLRes
	4,  // 20: auth.v1.OAuth2.OAuth2Login:output_type -> auth.v1.OAuth2LoginRes
	13, // 21: auth.v1.OAuth2.OAuth2PreLogin:output_type -> auth.v1.OAuth2PreLoginRes
	15, // 22: auth.v1.OAuth2.OAuth2BindLocal:output_type -> auth.v1.OAuth2BindLocalRes
	17, // 23: auth.v1.OAuth2.OAuth2CreateLocal:output_type -> auth.v1.OAuth2CreateLocalRes
	6,  // 24: auth.v1.OAuth2.BindOAuth2Account:output_type -> auth.v1.BindOAuth2AccountRes
	8,  // 25: auth.v1.OAuth2.UnbindOAuth2Account:output_type -> auth.v1.UnbindOAuth2AccountRes
	11, // 26: auth.v1.OAuth2.ListOAuth2Accounts:output_type -> auth.v1.ListOAuth2AccountsRes
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_oauth2_proto_init() }
func file_oauth2_proto_init() {
	if File_oauth2_proto != nil {
		return
	}
	file_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauth2_proto_rawDesc), len(file_oauth2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauth2_proto_goTypes,
		DependencyIndexes: file_oauth2_proto_depIdxs,
		EnumInfos:         file_oauth2_proto_enumTypes,
		MessageInfos:      file_oauth2_proto_msgTypes,
	}.Build()
	File_oauth2_proto = out.File
	file_oauth2_proto_goTypes = nil
	file_oauth2_proto_depIdxs = nil
}
